name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_KEY }}
        script: |
              cd /home/ec2-user/SejongGlobalBuddy
              git pull origin main
              ./gradlew clean build --info && echo "Build Success" || { echo "Build Failed"; exit 1; }
              sudo systemctl daemon-reload
              sudo systemctl restart sejongglobalbuddy
              exit 0
