name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd /home/ec2-user/SejongGlobalBuddy
          git pull origin main || { echo "Git pull failed"; exit 1; }
          source ~/.bash_profile
          ./gradlew clean copyReactBuildFiles build --info && echo "Build Success" || { echo "Build Failed"; exit 1; }

    - name: Restart service and check status
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_KEY }}
        script: |
          sudo systemctl daemon-reload
          sudo systemctl restart sejongglobalbuddy
          sudo systemctl status sejongglobalbuddy --no-pager
          sudo journalctl -u sejongglobalbuddy -n 20 --no-pager

